/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:63d5bfa8-b2ef-4619-bed3-8638dde5782b",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_QG8ToNMBl",
    "aws_user_pools_web_client_id": "2jtem39cnmdenf4nsu73v8e8ea",
    "oauth": {
        "domain": "headsupguys8658aeb1-8658aeb1-dev.auth.ca-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/signup?GoogleFlow=true/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS"
};


export default awsmobile;
